[package]
name = "adkg"
version = "0.1.0"
edition = "2021"


[dependencies]
avss = { path = "../avss" }
util = { path = "../util" }
rand = "0.8.5"
colored = "2.0.0"
termcolor = "1.1.2"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "bench"
harness = false